version: 0.2

env:
  git-credential-helper: yes

proxy:
    upload-artifacts: yes
    logs: yes
            
phases:
  install:
    runtime-versions:
      nodejs: 14
  build:
    commands:
      - cd website && yarn && yarn build
      - cd ../cdk && yarn && yarn build && yarn run cdk synth && yarn run deploy
